### ISSUE TITLE
OSX build: The command "tlmgr update --self" failed and exited with 2

### ISSUE THREAD

**Issue by gvegayon** [craigcitro/r-travis#174]
Without a clear reason, OSX build commands wont run using sudo. Linux build works fine but OSX is errored, here you can find the lines where the error shows: 

https://travis-ci.org/USCCANA/netdiffuseR/jobs/108368360#L66-L74

My .travis.yml is here (note that it does include the line sudo: required)

https://github.com/USCCANA/netdiffuseR/blob/e21f5b41f2048394b61e11f018b3b30d12be369c/.travis.yml

I also tried using matrix:include:osx:sudo (as you can see here https://github.com/USCCANA/netdiffuseR/blob/master/.travis.yml) without success.

```yml
matrix:
  include:
    - os: osx
      sudo: required
```

Am I doing something wrong here?

Thanks

**Comment by craigcitro** [comment]
Paging @jimhester who hit something else like this, I think?

**Comment by jimhester** [comment]
Sorry this was inadvertent breakage with my recent changes. https://github.com/jimhester/travis-build/commit/52eafd67d85045f31b35458fbcec4665851d1860 should fix the issue once it is merged and pushed to production.

**Comment by gvegayon** [comment]
Great, thanks!

George G. Vega Yon
+1 (626) 381 8171
http://www.its.caltech.edu/~gvegayon/

**Comment by gvegayon** [comment]
Now I'm getting "An error occurred while generating the build script."

https://travis-ci.org/USCCANA/netdiffuseR/jobs/110016615

Is this due to the update?

**Comment by paleo13** [comment]
I'm receiving this error too.

https://travis-ci.org/paleo13/rapr/jobs/110728413

**Comment by gvegayon** [comment]
Hey @jimhester ,

So the situation has improved, but now I'm getting the following error:

```sh
$ sudo 757 /usr/local/texlive/2015/tlpkg/
sudo: 757: command not found

The command "sudo 757 /usr/local/texlive/2015/tlpkg/" failed and exited with 1 during .
```

(See here https://travis-ci.org/USCCANA/netdiffuseR/jobs/111627951#L72) what can it be??

Thanks a lot for your help

**Comment by craigcitro** [comment]
@gvegayon I'm fairly sure it was a typo, and was fixed here: https://github.com/travis-ci/travis-build/pull/650

**Comment by paleo13** [comment]
I just restarted the job and now receive this error:

`
sudo chmod 757 /usr/local/texlive/2015/tlpkg/
chmod: /usr/local/texlive/2015/tlpkg/: No such file or directory

The command "sudo chmod 757 /usr/local/texlive/2015/tlpkg/" failed and exited with 1 during .
`

Is it possible that a latex is being installed elsewhere? 

See here for more info: https://travis-ci.org/paleo13/rapr/jobs/111632985

Thanks!

**Comment by jimhester** [comment]
@paleo13 That error should be fixed once https://github.com/travis-ci/travis-build/issues/654 is merged.

**Comment by paleo13** [comment]
Sorry to be a pain,

I am now receiving this error (see https://travis-ci.org/paleo13/rapr/jobs/111895051):

```
$ tlmgr update --self
tlmgr: package repository http://ftp.math.purdue.edu/mirrors/ctan.org/systems/texlive/tlnet
tlmgr: saving backups to /usr/local/texlive/2015basic/tlpkg/backups
/usr/texbin/tlmgr: create(tlpkg/tlpobj/texlive.infra.tlpobj) failed: Permission denied at /usr/local/texlive/2015basic/tlpkg/TeXLive/TLPOBJ.pm line 552.
The command "tlmgr update --self" failed and exited with 13 during .
```

I suspect line 424 in `lib/travis/build/script/r.rb` needs to be replaced with something like:

```
 sh.cmd 'sudo tlmgr update --self'
```

Or choosing a different set of permissions that let it write to this directory.

Thanks!

**Comment by jimhester** [comment]
Ok I have given up on trying to do this without sudo, should be fixed after https://github.com/travis-ci/travis-build/pull/657 is merged. May not be until Monday as Travis doesn't usually deploy on Fridays.

**Comment by paleo13** [comment]
Just wanted to follow up, I'm still receiving the error message but I don't think the pull request's gone through.

Let me know if there's any extra info I can provide that will help.

**Comment by gvegayon** [comment]
Reporting here, now I'm getting a different error:

```sh
$ sudo installer -pkg "/tmp/pandoc-1.15.2-osx.pkg"
installer: Error -target parameter required
...
The command "sudo installer -pkg "/tmp/pandoc-1.15.2-osx.pkg"" failed and exited with 255 during .
```

https://travis-ci.org/USCCANA/netdiffuseR/jobs/114177607#L95

**Comment by jimhester** [comment]
@gvegayon https://github.com/travis-ci/travis-build/pull/668 will fix that once it is merged...

**Comment by gvegayon** [comment]
Great! Thanks a lot for all the work!

George G. Vega Yon
+1 (626) 381 8171
http://www.its.caltech.edu/~gvegayon/

**Comment by jimhester** [comment]
This should now be fixed in production

**Comment by paleo13** [comment]
Hi,

Yeah it's now working (see https://travis-ci.org/paleo13/rapr/jobs/113577663)

Thanks!

**Comment by jimhester** [comment]
This can be closed, the issue is fixed.

**Comment by lcolladotor** [comment]
Hi @jimhester,

I'm getting a similar error to the one initially reported in this issue. See https://travis-ci.org/leekgroup/recount/builds/135994740#L390

The log shows:

```
$ tlmgr update --self
Unknown directive ...containerchecksum c59200574a316416a23695c258edf3a32531fbda43ccdc09360ee105c3f07f9fb77df17c4ba4c2ea4f3a5ea6667e064b51e3d8c2fe6c984ba3e71b4e32716955... , please fix it! at /home/travis/texlive/tlpkg/TeXLive/TLPOBJ.pm line 210, <$retfh> line 5579.
```

So it looks like it's not using `sudo` anymore. Is this due to an update? Or something I can fix by changing https://github.com/leekgroup/recount/blob/7a419f7f42df197e0efd11f52161cde4028d417a/.travis.yml

Best,
Leo

**Comment by berndbischl** [comment]
same problem here, and I guess for everybody

**Comment by craigcitro** [comment]
I'm guessing this is https://github.com/travis-ci/travis-ci/issues/6139 -- @jimhester does that sound plausible?

**Comment by jimhester** [comment]
Yes, it is the same issue, will be fixed once the PR is merged and deployed

**Comment by lcolladotor** [comment]
I can verify that everything works again. See https://travis-ci.org/leekgroup/recount/builds/136040524

**Comment by jstockwin** [comment]
@jimhester I seem to be getting a very similar issue again:

```
1.54s$ curl -fLo /tmp/texlive.tar.gz https://github.com/jimhester/ubuntu-bin/releases/download/latest/texlive.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   604    0   604    0     0   8187      0 --:--:-- --:--:-- --:--:--  9437
100 79.6M  100 79.6M    0     0  52.5M      0  0:00:01  0:00:01 --:--:-- 59.0M
4.27s$ tar xzf /tmp/texlive.tar.gz -C ~
$ export PATH=/$HOME/texlive/bin/x86_64-linux:$PATH
8.05s$ tlmgr update --self
TeX Live 2016 is frozen forever and will no
longer be updated.  This happens in preparation for a new release.
If you're interested in helping to pretest the new release (when
pretests are available), please read http://tug.org/texlive/pretest.html.
Otherwise, just wait, and the new release will be ready in due time.
tlmgr: package repository http://ctan.sharelatex.com/tex-archive/systems/texlive/tlnet (verified)
tlmgr: saving backups to /home/travis/texlive/tlpkg/backups
TLUtils::check_file: removing /tmp/xvsLT8uoe8/gE89fC0h4u/texlive.infra.tar.xz, sizes differ:
TLUtils::check_file:   TL=200472, arg=194264
TLPDB::_install_package: downloading did not succeed
tlmgr: Installation of new version of texlive.infra failed, trying to unwind.
[1/1, ??:??/??:??] update: texlive.infra [190k] (41280 -> 41476) ... tlmgr: Restoring old package state succeeded.
done
tlmgr: action update returned an error; continuing.
tlmgr: package log updated: /home/travis/texlive/texmf-var/web2c/tlmgr.log
tlmgr: An error has occurred. See above messages. Exiting.
The command "tlmgr update --self" failed and exited with 1 during .
Your build has been stopped.
```
https://travis-ci.org/jstockwin/EpiEstimApp/jobs/239272014#L465

Is anyone else having the same problem?

**Comment by taylor-arnold** [comment]
@jstockwin Yes, same issue here. I just saw that TeX Live 2017 was released today, so likely the cause of the problem.

**Comment by jbryer** [comment]
I can also report that I am getting this error today too with this repository: https://github.com/DAACS/documentation

```
$ tlmgr update --self
TeX Live 2016 is frozen forever and will no
longer be updated.  This happens in preparation for a new release.
If you're interested in helping to pretest the new release (when
pretests are available), please read http://tug.org/texlive/pretest.html.
Otherwise, just wait, and the new release will be ready in due time.
tlmgr: package repository http://ctan.sharelatex.com/tex-archive/systems/texlive/tlnet (verified)
tlmgr: saving backups to /home/travis/texlive/tlpkg/backups
TLUtils::check_file: removing /tmp/d8OWsc7489/h9dF2XyQ7G/texlive.infra.tar.xz, sizes differ:
TLUtils::check_file:   TL=200472, arg=194264
TLPDB::_install_package: downloading did not succeed
tlmgr: Installation of new version of texlive.infra failed, trying to unwind.
[1/1, ??:??/??:??] update: texlive.infra [190k] (41280 -> 41476) ... tlmgr: Restoring old package state succeeded.
done
tlmgr: action update returned an error; continuing.
tlmgr: package log updated: /home/travis/texlive/texmf-var/web2c/tlmgr.log
tlmgr: An error has occurred. See above messages. Exiting.
The command "tlmgr update --self" failed and exited with 1 during .
```
